server:
  port: 8989
  servlet:
    context-path: /cmfz
    jsp:
      init-parameters:
        development: true
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/cmfz
  mvc:
    view:
      suffix: .jsp
      prefix: /
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
mybatis:
  mapper-locations: com/baizhi/ly/mapper/*Mapper.xml
  type-aliases-package: com.baizhi.ly.entity
logging:
  level:
    com.baizhi.ly.dao: debug